#!/usr/bin/env ruby

loc = Dir.pwd.split('/')
unless loc[loc.size - 1] == 'bonus'
    STDERR.puts "ERROR:"
    STDERR.puts "\tYou must be in the 'bonus' folder to run the program,"
    STDERR.puts "\tbut you are at '#{Dir.pwd}'."
    exit 84
end

buffer = `npm --version`.split('.')
for i in 0..buffer.size - 1
    if i + 1 == buffer.size - 1
        break;
    end
    unless buffer[i].to_i.to_s == buffer[i]
        STDERR.puts "ERROR:"
        STDERR.puts "\tYou are missing prerequisites,"
        STDERR.puts "\tplease run this command:"
        STDERR.puts "\t> sudo apt-get install npm"
        exit 84
    end
end

system 'npm start'
